### PR TITLE
Run Integration Test in Separate Docker containers

### PR DESCRIPTION
**Pull request by jackzampolin**
# Faster Integration Tests

This PR adds the ability to run the integration tests in separate docker containers allowing the running of tests to be parallelized. I've provided a quick little CLI to help with running these:

```bash
$ ./test-launcher
BLOCKSTACK DOCKER TEST LAUNCHER:
  Working with Docker Images:
    build-image -> build the test container
    push-image   -> build and push tests image to container registry

  Running tests on local Docker daemon:
    run-one-local        -> run one test locally (pass test name)
    run-all-local        -> loop through the tests runing 8 at a time
    results-local        -> check results from finished tests
    write-local          -> write test results to a configured influx instance
    progress-local       -> log progress in the test suite
    cleanup-files-local  -> remove all files from test
    cleanup-docker-local -> cleanup docker containers from test

  Running tests against a Kubernetes Cluster:
    run-all-helm         -> use the helm chart in deployment/ to spin up a bunch of test containers
    run-one-helm         -> use the helm chart in deployment/ to spin up a single test container (pass name as arg)
    results-helm         -> check results from finished tests
 ```

### Build and push the image

To run all the tests have docker installed and start by running `$ ./test-launcher build-images`. This builds the docker container for testing off of the current branch. I have optimized the build to take maximum advantage of docker caching. The first build takes around 15-20 min. Subsequent builds take ~1-2 min. 

To push the images to quay, login (`docker login quay.io`) then run `$ ./test-launcher push-images`. This will build and push from the current branch.

### Run the tests

Once the images are built you can then run the tests. By default, the following command runs all the tests in `/integration_tests/blockstack_integration_tests/scenarios/` except the ones listed in `/integration_tests/blockstack_integration_tests/tests_skip.txt`.

```bash
$ ./test-launcher run-all-local &
```
This loops through the list of tests to run an spins up a separate container to run each one. The script limits the number of running containers to the number of logical CPU cores on the system. This is to prevent resource contention. If you run more than that then the calls to the `bitcoind` nodes in the test containers timeout. 

### Check testing progress

To check the progress of the tests while they are running there are two commands:

```bash
$ ./test-launcher progress-local
TotalTests: 244, Completed: 5%, InProgress: 3%, Remaining: 92%
$ ./test-launcher check-results
[ ] SUCCESS in 5m 44s -> /name_import_renew_transfer-ed93054
[ ] SUCCESS in 5m 33s -> /name_import_renew_revoke-ed93054
[ ] SUCCESS in 4m 55s -> /name_import_renew_nextepoch-ed93054
[X] FAILURE in 1m 54s -> /name_import_renew-ed93054 (docker logs 1ec23bcfda71)
[ ] SUCCESS in 7m 55s -> /name_import_nextepoch_import_expire_reregister-ed93054
[ ] SUCCESS in 8m 28s -> /name_import_import_expire_reregister-ed93054
[ ] SUCCESS in 6m 45s -> /name_import_expire_reregister-ed93054
[ ] SUCCESS in 5m 3s -> /name_import_expire_isdead-ed93054
[ ] SUCCESS in 8m 23s -> /name_import-ed93054
[ ] SUCCESS in 4m 28s -> /issue469_1-ed93054
[X] FAILURE in 3m 36s -> /convert_regtest_to_mainnet_name-ed93054 (docker logs 7bf0a5c5e2ba)
...
```
The first gives the progress of the current test run. The second iterates through the exited tests and outputs the results. It also gives you the command to check logs for the failed tests: `docker log <testContainerID>`. 

You can also run individual tests with the `$ ./test-launcher run-one-local <scenario>`. 

### Troubleshoot

If you need to check the contents of the `/tmp` directory to make sure the test is properly configured, those results are stored in `/integration_tests/test-out/<gitBranch>-<gitCommit>/<testName>`. For example when running tests on this branch, the files for the `name_import` test live in `/integration_tests/test-out/develop-jz-dockerintegration-ed93054/name_import`. This folder structure allows for the complete sandboxing of tests by git commit. 

### Cleanup

Once the tests have completed and the results have been checked you can cleanup the artifacts left on the host by running the following:

```bash
# Delete all the data from the /tmp directories of the tests
$ ./test-launcher cleanup-files-local

# Delete the stopped docker containers and their logs
$ ./test-launcher cleanup-docker-local
``` 

### Kubernetes integration

I've also done some work to run this on an autoscaling Kubernetes cluster. I'll have more on that once the work is complete. I'm using [`helm`](https://github.com/kubernetes/helm) as a templating engine to run each test in a separate pod. I'll do a more complete writeup on how I've got the cluster configured at another time.

### Automation

We could automate this process from pushes to the quay image repo -
 https://docs.quay.io/guides/notifications.html

Full suite took ~5hrs on my older MBP.
Full suite took ~2hrs on a 16 core azure box.
While I have not been able to get the full suite running in Kube (just 80%) it looks to finish in under an hour.

### CODE REVIEW

**Comment by jackzampolin** [comment]
Running more than 1 container per core results in timeouts and failed tests.

**Comment by jackzampolin** [comment]
Tests running on 16 CPU 32 GB Azure instance completed in 2 hours. Failures on the following tests:

```
$ ./test-launcher check-results | grep "FAILURE"
[X] FAILURE in 2m 28s -> /name_preorder_register_update_nonstandard_zonefile-9c91140 (docker logs de992ffa90e4)
[X] FAILURE in 1m 17s -> /name_preorder_register_update_deletemutable-9c91140 (docker logs 6b7cf6d92afb)
[X] FAILURE in 1m 18s -> /name_preorder_register_update_deletemutable_nodatakey-9c91140 (docker logs a70506763483)
[X] FAILURE in 4m 28s -> /name_preorder_register_update_datakey_migration-9c91140 (docker logs dc7a6560c841)
[X] FAILURE in 7m 25s -> /name_preorder_register_update_atlas_churn-9c91140 (docker logs 5212752821bb)
[X] FAILURE in 1m 33s -> /name_preorder_register_update_app_datastore_stale_file-9c91140 (docker logs 52ed9750ab23)
[X] FAILURE in 1m 31s -> /name_preorder_register_update_app_datastore_stale_directory-9c91140 (docker logs 558d2bd5ca8f)
[X] FAILURE in 1m 27s -> /name_preorder_register_update_app_datastore_rmtree-9c91140 (docker logs 8d7386596253)
[X] FAILURE in 1m 11s -> /name_preorder_register_portal_datastore-9c91140 (docker logs 5ed1ee40593c)
[X] FAILURE in 1m 7s -> /name_preorder_register_portal_auth-9c91140 (docker logs bc126b7d8344)
```

**Comment by kantai** [comment]
These integration tests are currently not working (some of them are testing functionality that has changed a lot or is not fully implemented in master or develop)
```
name_preorder_register_update_app_datastore_rmtree
name_preorder_register_update_app_datastore_stale_directory
name_preorder_register_update_app_datastore_stale_file
name_preorder_register_update_datakey_migration
name_preorder_register_update_deletemutable
name_preorder_register_update_deletemutable_nodatakey
name_preorder_register_update_nonstandard_zonefile
```

However, the `atlas_churn`, `portal_auth`, and `portal_datastore` tests *should* work. The portal tests require that node be installed. Not sure why atlas_churn would be failing. Will need to see logs.

**Comment by cryptomental** [comment]
Hi. I jumped in here by accident and learnt a few neat tricks from this pr. You might want to add run-selected command that would accept a list of tests or better regexps of test case names to execute. Like in the case above to re-run just the failing ones.  Also a small inconsistency: help message says "loop through the tests running 20 at a time" while it is limited to $numContainers. Anyway, a good job.

**Comment by jackzampolin** [comment]
Thanks @cryptomental 😊 What did you learn?

Also thanks for the point out on the typo! I've also added a `run-one` per your suggestion. One reason I'm not going to add the `run-selection` is that I'm planning on doing the work to make this run on Kubernetes or another orchestrator so that we can autoscale the hosts and run the whole suite at once. Were you able to get it running ok? 

Also @kantai I've removed the `/tmp` mount for the `run-all` command and left it in the `run-one`. I'm thinking we automatically re-run failed tests with the volume mounts in a future version of this.

**Comment by cryptomental** [comment]
@jackzampolin I learnt how to easily solve storing results for multiple branches. If everyone has a dev branch then with branch-git-hash folder naming scheme it's really easy to keep track on test results. It gave me an idea that with a simple script you can additionally get a comparison of the code changes almost out of the box and perhaps even start meld / p4merge. Currently I am not using kubernetes but Atlassian CI (Bamboo) that orchestrates containers. This is for embedded projects so it is a different story as I have to use yocto and most of the test time is spent for workspace bootstrap and building custom images. 

Anyway, I noticed that blockstack is a quite cool project, I will likely jump around and try tutorials this month.

**Comment by kantai** [comment]
Added some changes for supporting the blockstack.js and blockstack-storage-js integration tests. This dockerized integration test framework is awesome. A 2 hour test suite is *much* better than a 16 hour test suite.

**Comment by jackzampolin** [comment]
@cryptomental Awesome! If you need any help hit us up on our [forum](https://forum.blockstack.org) or join our [slack channel](http://chat.blockstack.org/). I'm always hanging out on there.

@kantai Thanks!

**Comment by jackzampolin** [comment]
Updated PR comment above with current info.

**Comment by jackzampolin** [comment]
Ok so getting blocked on reporting. I'll describe what I'm running into and potential ways around the issue. Sometimes tests hang. Many times with: 

```
[2017-09-06 01:04:59,722] [DEBUG] [atlas:2915] (1.139702080444160) localhost:16264: revalidate old peers
``` 

What is the cause of this? In the Docker version this is difficult to deal with. The problem is especially difficult on the distributed version of tests. This is because when tests are hanging many of them exit and the cluster begins to scale down. This makes it nigh impossible to get the test results in bash.

One potential way around here would be to have a flag in the `blockstack-test-scenario` command that allows for posting the testing data to a database. We could use the one at `monitoring.technofractal.com` ([client](http://github.com/influxdata/influxdb-python)) and get better results out of tests without a ton of logic in the `test-launcher`. This would make getting test runtime, stats from individual tests (something common between all?) and other information out of the tests possible. It would also significantly simplify reporting. I think everything I need is in the [`__main__`](https://github.com/blockstack/blockstack-core/blob/master/integration_tests/bin/blockstack-test-scenario#L1113) function. 

This gets to the question of where do we want the reporting to go? In the current version of the test suite it gets either output to the command line or posted to `monitoring.technofractal.com`. Ideally we will store each test run and stats in a database to allow for easy cross test comparisons and tracking of failures over time. If we can get the testing data to the monitoring database it would make outputting the test runs to slack trivial.

Does this approach sound OK @kantai @jcnelson ?

**Comment by kantai** [comment]
Merging into develop now. This improves the integration tests a ton, thanks @jackzampolin!

**Pull request merged**
