### PR TITLE
Decouple pieces of the API 

### PR DESCRIPTION
**Pull request by jackzampolin**
I've done some work to begin decoupling the Blockstack API. There is a docker compose file that sets up the environment.

The road block I'm running into right now is that the `BASE_API_URL` from the `config.py` isn't being used and the server is trying to connect to `localhost:6270` instead of `http://blockstack-api:6270`.

### CODE REVIEW

**Comment by kantai** [comment]
Thanks for this @jackzampolin!

I'll take a look into the `BASE_API_URL` option tomorrow morning.

**Comment by kantai** [comment]
What commands are you using to run these containers?

**Comment by jackzampolin** [comment]
```
$ cd api
$ docker-compose up --build
```

**Comment by kantai** [comment]
Pushed some changes. I think the root issue was that `api/requirements.txt` pip installs blockstack. The subsequent `pip install .` command will skip overwriting that package unless you supply the `--upgrade` flag. There were a couple of other small issues preventing it from running (the `/tmp` mounting issue, missing imports after clearing out variables from config.py) and I needed to run `./ops init-api` before it would run.

Something that's probably worthwhile would be making some of the important `config.py` settings actually configurable via environment variables.

**Comment by jackzampolin** [comment]
Ok so after fighting this on mac for a while I decided to boot it up on ubuntu and its working fine. I don't think we need to target mac for this so I'll continue dev there.

**Comment by jackzampolin** [comment]
Ok! I've got all those settings set to defaults and now able to be set via env. The next step could be to start transitioning the indexing jobs to write to mongo directly. I've got this PR on the agenda for the Engineering meeting tomorrow so we can discuss there!

https://github.com/blockstack/blockstack/issues/400

**Comment by kantai** [comment]
Okay -- I've added a container for the indexer which will update the mongodb -- I haven't tested the cronjobs for the full re-indexing operation -- those take a while (hour-ish, depending on how this gets deployed) to run. _Plus_ you may need to configure the search indexer's `client.ini` so that it actually links to the core node you want it to talk to.

For now, on start-up it initiates the index with a fixture-set. You can test a query:

```$ curl localhost:3000/v1/search?query=dushan```

**Comment by jackzampolin** [comment]
Getting this running so the indexer can work over the weekend.

**Comment by jackzampolin** [comment]
Ok so I have this setup running right now, but the docker-compose file here isn't updated. If you would like details about the running setup they are here: https://github.com/blockstackinc/devops/tree/master/core.blockstack.org/docker

I will be pushing a few more commits to this.

**Comment by kantai** [comment]
This setup looks like its working -- thanks for this! Reproducible deployment is a lifesaver. Let me know when you want me to merge into `develop` @jackzampolin.

**Comment by jackzampolin** [comment]
Lets do it. Once that happens I'll get CI setup for the containers and then get it deployed live.

**Pull request merged**
