### PR TITLE
Feature/rest subdomain ops

### PR DESCRIPTION
**Pull request by jcnelson**
Adds support for the `GET /v1/subdomains/{:txid}` endpoint, so you can see which subdomain operations were processed with this transaction. Example on my local node:

```
$ curl -s http://localhost:6270/v1/subdomains/531d02e4f1cff8a29d3bdee02aaa63c32f5be6dbec2fd7c2b80fbd8e4878c255 | jq
[
  {
    "accepted": 1,
    "block_height": 545901,
    "domain": "id.blockstack",
    "fully_qualified_subdomain": "dinosath.id.blockstack",
    "missing": "",
    "owner": "1Q1EeRrRA9YPEV98doUXFPHC7qVubLHbQm",
    "parent_zonefile_hash": "92d6b2fc656f25503a0cc7d57ddd45738af41358",
    "parent_zonefile_index": 95728,
    "resolver": "https://registrar.blockstack.org",
    "sequence": 0,
    "signature": "None",
    "txid": "531d02e4f1cff8a29d3bdee02aaa63c32f5be6dbec2fd7c2b80fbd8e4878c255",
    "zonefile_hash": "661a8472824ceec21ede4c5fba3b71893177a1bc",
    "zonefile_offset": 0
  },
  {
    "accepted": 1,
    "block_height": 545901,
    "domain": "id.blockstack",
    "fully_qualified_subdomain": "scribendi.id.blockstack",
    "missing": "",
    "owner": "1PWaPygCBCgkgFDvJ8C8Ubn9mHZjZEijFD",
    "parent_zonefile_hash": "92d6b2fc656f25503a0cc7d57ddd45738af41358",
    "parent_zonefile_index": 95728,
    "resolver": "https://registrar.blockstack.org",
    "sequence": 0,
    "signature": "None",
    "txid": "531d02e4f1cff8a29d3bdee02aaa63c32f5be6dbec2fd7c2b80fbd8e4878c255",
    "zonefile_hash": "be41d22958d8fd243eb70c600b53ddf802b04468",
    "zonefile_offset": 1
  },
  {
    "accepted": 1,
    "block_height": 545901,
    "domain": "id.blockstack",
    "fully_qualified_subdomain": "jedschmidt.id.blockstack",
    "missing": "",
    "owner": "13QW6hxWHKKCyj9S5AX6n1UTGjXtVqjuFx",
    "parent_zonefile_hash": "92d6b2fc656f25503a0cc7d57ddd45738af41358",
    "parent_zonefile_index": 95728,
    "resolver": "https://registrar.blockstack.org",
    "sequence": 0,
    "signature": "None",
    "txid": "531d02e4f1cff8a29d3bdee02aaa63c32f5be6dbec2fd7c2b80fbd8e4878c255",
    "zonefile_hash": "988b8750eb38f7b779d00dc8fdfe507c80dbad37",
    "zonefile_offset": 2
  },
  {
    "accepted": 1,
    "block_height": 545901,
    "domain": "id.blockstack",
    "fully_qualified_subdomain": "codysork.id.blockstack",
    "missing": "",
    "owner": "1MW1YptA7aXdBqwYRtG4shYwnr5bZskDV9",
    "parent_zonefile_hash": "92d6b2fc656f25503a0cc7d57ddd45738af41358",
    "parent_zonefile_index": 95728,
    "resolver": "https://registrar.blockstack.org",
    "sequence": 0,
    "signature": "None",
    "txid": "531d02e4f1cff8a29d3bdee02aaa63c32f5be6dbec2fd7c2b80fbd8e4878c255",
    "zonefile_hash": "a988a1d680bedcac8e47e06a6dc2f26f596f60ea",
    "zonefile_offset": 3
  }
]
```

Would love to get this merged in for the new explorer.  CC @hstove @kantai

### CODE REVIEW

**Comment by hstove** [comment]
This is extremely helpful. Thank you!!

**Comment by jcnelson** [comment]
You're welcome!  Can you approve the PR?

**Comment by kantai** [comment]
I'm testing this now -- might have an update to the integration tests Dockerfile.

**Comment by kantai** [comment]
This looks good to me, and the tests worked on my end.

I updated the integration testing dockerfile so that it installs the necessary nodejs globals for integration tests.

**Pull request merged**
