### PR TITLE
REPL and eval_raw local commands

### PR DESCRIPTION
**Pull request by zone117x**
### Initial REPL implementation
Implement a new `local` command `local repl`. 

Uses the rust stdin/stdout so input interactivity is limited -- notably input cursor operation. The SDK project can wrap this stdin/out pipe to provide a more full-featured terminal lib. 

Initial implementation is currently stateless, but still quite useful for local dev & testing purposes since it performs type checking and (stateless) evals on expressions. 

Next iterations for providing state require something like:
* Execute evals within an implicit `transient` contract state and commit the savepoints. 
* Allow top-level (contract level) expressions and have them "appended" to `transient` contract source / ast. 

Providing REPL support for multiple contracts requires something like:
* Define a special function (available only in local dev / repl env) for defining & deploying a new contract, with the given name and source-expression. 
* Define another similar special function for switching context between the currently executing contract. 

A `local eval_raw` command is also implemented which provides the same ability to typecheck and execute a raw expression without having to provide any state or db initialization.

### CODE REVIEW

**Comment by jcnelson** [comment]
Actually, one quick thing -- can you remove the warnings you see from CircleCI?

**Comment by kantai** [comment]
> Actually, one quick thing -- can you remove the warnings you see from CircleCI?

I think the circle executor needs to be updated to run tests singly-threaded, since it's failing on the networking tests.

**Comment by jcnelson** [comment]
@kantai https://github.com/blockstack/blockstack-core/pull/964

**Comment by kantai** [comment]
This may be a good opportunity for us to replace uses of the `transient` contract name with a contract name containing illegal characters, e.g., `:transient:` or `_local_`.

**Comment by jcnelson** [comment]
That's a good point -- we don't want a typo to accidentally create a contract.

**Pull request merged**
