### PR TITLE
Add /v1/index_files endpoint

### PR DESCRIPTION
**Pull request by kantai**
Implements #901 ---

This adds a new endpoint: `/v1/index_files`, which can be configured to return URLs for getting search index dumps. By default (if left unconfigured), this returns 404.

You can test this behavior locally:

```bash
$ cd blockstack-core
$ pip install .
$ pip install -r ./api/requirements.txt
$ FLASK_APP=api.server flask run
```

Then:

```http
$ curl localhost:5000/v1/index_files -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v1/index_files HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 404 NOT FOUND
< Content-Type: application/json
< Content-Length: 62
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: OPTIONS, HEAD, POST, GET
< Access-Control-Max-Age: 21600
< Cache-Control: public, max-age=600
< Server: Werkzeug/0.14.1 Python/2.7.15rc1
< Date: Fri, 01 Feb 2019 15:05:22 GMT
< 
{"error":"Index file serving not configured on this server."}
```

If you set the environment variables when running:

```bash
$ export BSK_API_BLOCKCHAIN_URL="https://storage.googleapis.com/blockstack-search_indexer_data/blockchain_data.json"
$ export BSK_API_PROFILE_URL="https://storage.googleapis.com/blockstack-search_indexer_data/profile_data.json"
$ FLASK_APP=api.server flask run
```

Then you should see the response:

```json
$ curl localhost:5000/v1/index_files -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /v1/index_files HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: application/json
< Content-Length: 212
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: OPTIONS, HEAD, POST, GET
< Access-Control-Max-Age: 21600
< Cache-Control: public, max-age=600
< Server: Werkzeug/0.14.1 Python/2.7.15rc1
< Date: Fri, 01 Feb 2019 15:06:27 GMT
< 
{
  "indexes": {
    "blockchainData": "https://storage.googleapis.com/blockstack-search_indexer_data/blockchain_data.json",
    "profileData": "https://storage.googleapis.com/blockstack-search_indexer_data/profile_data.json"
  }
}
```

### CODE REVIEW

**Comment by jcnelson** [comment]
Thanks @kantai!

From a developer UX, do you think it would make more sense to have Blockstack Core reply with HTTP 302 for the index files?  We could create an endpoint for each file, and have the Core endpoint 302 the request to the actual data.  For example:

* `/v1/index_files/blockchain` would 302 to the `blockchainData` URL
* `/v1/index_files/profiles` would 302 to the `profileData` URL

**Comment by kantai** [comment]
Yeah, 302'ing is fine by me.

**Comment by kantai** [comment]
New behavior:


```
$ curl -s -L localhost:5000/v1/index_files/blockchain -I
HTTP/1.0 302 FOUND
Content-Type: application/json
Content-Length: 104
Location: https://storage.googleapis.com/blockstack-search_indexer_data/blockchain_data.json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, POST, GET
Access-Control-Max-Age: 21600
Cache-Control: public, max-age=600
Server: Werkzeug/0.14.1 Python/2.7.15rc1
Date: Fri, 01 Feb 2019 15:44:40 GMT

HTTP/2 200 
x-guploader-uploadid: AEnB2UrClL5C3U-hDLh95uThu1WLLYl_03bCUqQRVjczSvGGz_GtV9Q6Iky6w4qqgMTF-YMqZmjUr1d7kb7Hra_jga857XDSYg
expires: Fri, 01 Feb 2019 16:44:36 GMT
date: Fri, 01 Feb 2019 15:44:36 GMT
last-modified: Fri, 01 Feb 2019 14:00:08 GMT
etag: "67d4f6210addcb751cdb0622304a569a"
x-goog-generation: 1549029608727703
x-goog-metageneration: 2
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 2519794
content-type: application/json
x-goog-hash: crc32c=PiaBng==
x-goog-hash: md5=Z9T2IQrdy3Uc2wYiMEpWmg==
x-goog-storage-class: REGIONAL
accept-ranges: bytes
content-length: 2519794
server: UploadServer
cache-control: public, max-age=3600
age: 4
alt-svc: quic=":443"; ma=2592000; v="44,43,39"

aaron@cornelius $ curl -s -L localhost:5000/v1/index_files/profiles -I
HTTP/1.0 302 FOUND
Content-Type: application/json
Content-Length: 98
Location: https://storage.googleapis.com/blockstack-search_indexer_data/profile_data.json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, HEAD, POST, GET
Access-Control-Max-Age: 21600
Cache-Control: public, max-age=600
Server: Werkzeug/0.14.1 Python/2.7.15rc1
Date: Fri, 01 Feb 2019 15:45:01 GMT

HTTP/2 200 
x-guploader-uploadid: AEnB2UoimPVwNedUcL1FmDYJU1rfxmkeoRlJe_tg_pk7sC0E3KSNIen5aKQjkz2J0KURLGKg9p8teM9vk6oEt168NKw-rGsMvx52re2ZH1Pm0vExmgxV01A
expires: Fri, 01 Feb 2019 16:45:01 GMT
date: Fri, 01 Feb 2019 15:45:01 GMT
cache-control: public, max-age=3600
last-modified: Fri, 01 Feb 2019 14:00:08 GMT
etag: "6c74574dc4fb921e6214cd7576a73a19"
x-goog-generation: 1549029608074582
x-goog-metageneration: 2
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 62807322
content-type: application/json
x-goog-hash: crc32c=YvKAkA==
x-goog-hash: md5=bHRXTcT7kh5iFM11dqc6GQ==
x-goog-storage-class: REGIONAL
accept-ranges: bytes
content-length: 62807322
server: UploadServer
alt-svc: quic=":443"; ma=2592000; v="44,43,39"
```

And if you're interested in the content of those 302 responses:

```
$ curl -s localhost:5000/v1/index_files/profiles | jq .
{
  "profileData": "https://storage.googleapis.com/blockstack-search_indexer_data/profile_data.json"
}

$ curl -s localhost:5000/v1/index_files/blockchain | jq .
{
  "blockchainData": "https://storage.googleapis.com/blockstack-search_indexer_data/blockchain_data.json"
}
```

**Comment by jcnelson** [comment]
Looks great!  Could you also update the `api/README.md` file to document these environment variables?  Then I'll merge it.

**Comment by kantai** [comment]
Readme updated.

**Comment by jcnelson** [comment]
Cool, looks good to me :+1: Feel free to merge it

**Pull request merged**
