### PR TITLE
docs Modifications for new docs site 

### PR DESCRIPTION
**Pull request by moxiegirl**
This is a WIP progress PR of the changes I am making in support of the new docs site.  This material consists of:

* addition of new subdirectories
* splitting large files into individual files
* addition of frontmatter
* minor copy changes in support of new material
* Removing old cli material per Jude

Once I have updated all the downstream repos, I expect to make the docs site live and follow on immediately within the hour merging this PR. 

**NOTE**: Links are broken in this existing PR's material. I am aware of that and will be fixing those before asking for a formal review.

Signed-off-by: moxiegirl <mary@blockstack.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@kantai @jcnelson please go ahead and merge this.  The site with these changes are live. 

You'll need to rebuild the API --- I assume that is in a deploy script. I've tested the APIs locally.

**Comment by jcnelson** [comment]
I see you deleted and/or renamed a few things.  Can you please add "stub" files back in that contain something like `This documentation has moved to ...`?

**Comment by moxiegirl** [comment]
@jcnelson I'll add a link in the readme to docs.blockstack.org.  The goal here is to direct people to the docs not to keep them in the repo.

**Comment by jcnelson** [comment]
> The goal here is to direct people to the docs not to keep them in the repo.

I agree.  However, this does not change the fact that there are direct links out there to files like `atlas_network.md` or `faq_technical.md` that will now break as a result of this reorganization.  We should re-create these files with text like that in the top-level README.md.

**Comment by moxiegirl** [comment]
@jcnelson The top-level README.md is still there. It directs the users to the website.

**Comment by jcnelson** [comment]
Here's an example: https://forum.blockstack.org/t/boundaries-between-bns-virtualchain-and-atlas/6250.  We want to make that when a user posts links to our existing docs, others reading it won't get 404'ed.  The (soon-to-be-removed) docs can contain text to the effect of "Go Here for the Latest Docs", but they shouldn't just disappear.

**Comment by moxiegirl** [comment]
I understand what you want @jcnelson but I'm saying that I can't build redirects for moved git hub pages.  So, that would require finding every link ever made to the forum to any of the files in our repository and then keeping a page around just to support it. 

What would be in the page? A pointer to a new page or the old content? Keeping the old content is confusing and it relies on the user _noticing_ the deprecation.

The '404' makes it clear that the content is not longer viable. They user goes to the repo sees the README and is directed to the docs.  Or, alternatively, the user posts on the forum --- the doc is missing, asks for an update which tells us the topic is interesting and we post a link to the new page on the forum again, directing a user to the docs.

**Comment by moxiegirl** [comment]
We can, in discourse, look for a particular string and then replace it.  So, I can look at doing some processing of discourse to locate the posts with all references to github files.

**Comment by aulneau** [comment]
I agree with Jude, it's pretty important to not just use the 404 and instead keep the same structure, but direct users to the new site. Here's an example from a very popular css-in-js lib -> https://github.com/styled-components/styled-components/blob/master/docs/theming.md

**Comment by moxiegirl** [comment]
@jcnelson @aulneau I've talked with Aaron also. So, I will add these pointer files back in with a notice to go to docs.blockstack.org.  After a year, I'll remove them so that we are not maintaining them indefinitely.

**Comment by moxiegirl** [comment]
@kantai @jcnelson Final review, please.

**Comment by jcnelson** [comment]
Thanks @moxiegirl, really appreciate it!  Looks good to me :+1:

**Pull request merged**
