### PR TITLE
Add the packaging metadata to build the blockstack-core snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

To test it in an Ubuntu 16.04 machine:

```
$ sudo apt install git snapcraft
$ git clone https://github.com/elopio/blockstack-core
$ cd blockstack-core
$ git checkout snapcraft
$ cd images/snap
$ snapcraft
$ sudo snap install *.snap --dangerous
$ blockstack.server start
$ blockstack lookup timblee.id
```

If you have any questions or comments, please let me know.

**Comment by elopio** [comment]
ping. Anybody available to review this?

We are already have some interesting blockchain projects, like parity, bitcoin, nanowallet, dash, solidity... and they are getting some nice download stats. I would love all the ubuntu users to be able to discover and install blockstack.

Here you can see the other snaps in the store: https://uappexplorer.com/snaps
And we also have a new service, that will take care of building and publishing automatically for you: https://build.snapcraft.io
Take a look!

pura vida.

**Comment by kantai** [comment]
Hi @elopio -- would be happy to include some metadata for a snap build, though I think we won't have the bandwidth (for the time being) of supporting and maintaining a snap distribution.

Reviewing this PR, though, the metadata is based on an older version of core-- the server command in the snap tries to call `blockstack-server`, which is now deprecated in favor of the `blockstack-core` command. If you update, I'll test and merge the metadata into develop.

Thanks!

**Comment by elopio** [comment]
Hello @kantai!

I've updated the snap. And I would be happy to maintain this one in the store, organize the testing and promote it in our community. The work you are doing is super exciting to me, and it could serve as a good test subject for you. If you get good stats and feedback, maybe it would be easier for you to assign some resources to package and maintain the browser. 

The only detail I would ask to make my life easier maintaining it is to move the snapcraft.yaml out of the images directory. That will let me use the tools we have for continuous delivery. Otherwise I would have to write my own scripts to do it on travis or something like that. What do you think?

pura vida

**Comment by jackzampolin** [comment]
Hey @elopio! Thanks again for the PR. Can you add a quick readme with some of the above info ☝️ at `images/snap/README.md`?

**Comment by elopio** [comment]
@jackzampolin I've moved the dir, and added the README.
Once I push it to the store, I will add to the README:

    sudo snap install blockstack

**Comment by jackzampolin** [comment]
@elopio Just pinging you on this real quick!

**Comment by elopio** [comment]
@jackzampolin pong.

**Comment by jackzampolin** [comment]
@elopio Can you push those changes up to this branch so I can merge it?

**Comment by elopio** [comment]
@jackzampolin oh, lol. I'm sorry, I totally forgot to push. It should be ready now.

**Comment by jackzampolin** [comment]
@elopio Thank you so much for this! Going to go ahead and merge!

**Pull request merged**
